
name: Publish Nugets

on:
  release:
    types: [published]

jobs:
  build-and-push:

    name: Build Core
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: |
        nuget restore
        msbuild Mvx.Forms.PageWrapper/Mvx.Forms.PageWrapper.csproj /verbosity:normal /t:Rebuild /t:Pack /p:Configuration=Release
    - name: NuGet push
      run: dotnet nuget push Mvx.Forms.PageWrapper/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json